//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomatioonWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICILAR
    {
        public int ID { get; set; }
        public string KULLANICIAD { get; set; }
        public string KULLANICISOYAD { get; set; }
        public string KULLANICITC { get; set; }
        public string KULANICIMAIL { get; set; }
        public string KULLANICITEL { get; set; }
        public Nullable<double> KULLANICICEZA { get; set; }
    }
}
