//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomatioonWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONELLER
    {
        public int ID { get; set; }
        public string PERSONELAD { get; set; }
        public string PERSONELSOYAD { get; set; }
        public string PERSONELTC { get; set; }
        public string PERSONELTEL { get; set; }
        public string PERSONELMAIL { get; set; }
        public string PERSONELKULLANICIAD { get; set; }
        public string PERSONELSIFRE { get; set; }
    }
}
